version: '3.4'
services:
#  # back-end api built with golang
#  golang:
#    build:
#      context: golang
#      dockerfile: Dockerfile
#      target: dev
#    volumes:
#      - ./golang:/root
#    ports:
#      - "5000:5000"
#    env_file: .env
#    depends_on:
#      - postgres

  # postgres is our primary data store
  postgres:
    container_name : postgres
    image: postgres:10.6-alpine
    environment:
      - POSTGRES_DB=invitmedb
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/setup_database.sql:/docker-entrypoint-initdb.d/schema
      - ../pgdb:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - "3456:3456"
    container_name: redis

#  # nginx is used for ssl termination
#  nginx:
#    build:
#      context: nginx
#      target: dev
#    ports:
#      - "443:443"
#    depends_on:
#      - golang